name: PDF in ubuntu

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Generate Example examples
    runs-on: ubuntu-latest
    timeout-minutes: 200
    steps:
      - uses: actions/checkout@v4

      - name: Install fonts (Times New Roman, SimSun, SimHei, KaiTi)
        run: |
          mkdir -p ~/.local/share/fonts/
          # https://github.com/Haixing-Hu/latex-chinese-fonts font
          wget https://github.com/Haixing-Hu/latex-chinese-fonts/raw/refs/heads/master/english/Serif/TimesNewRoman.ttf -O ~/.local/share/fonts/TimesNewRoman.ttf
          wget https://github.com/Haixing-Hu/latex-chinese-fonts/raw/refs/heads/master/chinese/%E5%AE%8B%E4%BD%93/SimSun.ttc -O ~/.local/share/fonts/SimSun.ttc
          wget https://github.com/Haixing-Hu/latex-chinese-fonts/raw/refs/heads/master/chinese/%E9%BB%91%E4%BD%93/SimHei.ttf -O ~/.local/share/fonts/SimHei.ttf
          wget https://github.com/Haixing-Hu/latex-chinese-fonts/raw/refs/heads/master/chinese/%E6%A5%B7%E4%BD%93/Kaiti.ttf -O ~/.local/share/fonts/Kaiti.ttf
          fc-cache -fv

      - name: Install latex (texlive-full)
        run: |
          sudo apt install texlive-full

      - name: Make pdf
        run: |
          make

      - name: Upload target example
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: exammaple docuemnts
          path: build/main.pdf
